#!/bin/bash
HIGH_RES_SIZE=12
START_COORDS="48.5005149839192 235.1816607162"
DESTINATION_COORDS="21.925 202.234"

./build/bin/pathfinder_cli -p ${HIGH_RES_SIZE} --navigate ${START_COORDS} ${DESTINATION_COORDS} --use_cached_planet --hardcoded Final
